stages:
  - lint
  - test
  - build

Lint:
  stage: lint
  image: python:3.12
  script:
    - pip install flake8
    - flake8

Test:
  stage: test
  image: python:3.12
  script:
    - pip install -r server/requirements.txt
    - pip install pytest
    - python3 -m pytest server/

Build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo Building
