version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  cache:
    image: redis
    container_name: cache

  client:
    build: client/
    container_name: client
    ports:
      - 3000:3000
    environment:
      - API_BASE_URL=${API_BASE_URL}

  server:
    build: server/
    container_name: server
    volumes:
      - ./media:/media
    depends_on:
      - database
      - cache
      - client
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env