version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=enigma
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build: client/
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:8000
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000

  server:
    build: server/
    container_name: server
    volumes:
      - ./media:/media
    depends_on:
      - database
      - client
    ports:
      - ${PORT}:${PORT}
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT}
      - RELOAD=${RELOAD}
      - DEBUG=${DEBUG}
      - DB_URL=${DB_URL}
    command: ["python", "run.py"]