version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  cache:
    image: redis
    container_name: cache

  client:
    build: client/
    container_name: client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - NUXT_HOST=${CLIENT_HOST}
      - NUXT_PORT=${CLIENT_PORT}

  server:
    build: server/
    container_name: server
    volumes:
      - ./media:/media
    depends_on:
      - database
      - cache
      - client
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_RELOAD=${SERVER_RELOAD}
      - DEBUG=${DEBUG}
      - DB_ENGINE=${DB_ENGINE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}