version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - envs/docker/.db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  client:
    build: client/
    container_name: client
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      - API_BASE_URL=http://${SERVER_HOST}:${SERVER_PORT}
      - NUXT_HOST=${CLIENT_HOST}
      - NUXT_PORT=${CLIENT_PORT}

  server:
    build: server/
    container_name: server
    volumes:
      - ./media:/media
    depends_on:
      - database
      - client
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - HOST=${SERVER_HOST}
      - PORT=${SERVER_PORT}
      - RELOAD=${SERVER_RELOAD}
      - DEBUG=${SERVER_DEBUG}
      - DB_URL=${DB_ENGINE}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}