stages:
  - lint
  - test
  - build

Lint:
  stage: lint
  image: python:3.12
  script:
    - pip install flake8
    - flake8

Test:
  stage: test
  image: python:3.12
  script:
    - pip install -r server/requirements.txt
    - pip install pytest
    - python3 -m pytest server/

Build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

    - cp $ENV_FILE .env
  script:
    - docker-compose build
    
    - docker tag enigma-server:latest $CI_REGISTRY/$CI_REGISTRY_USER/enigma/server:latest
    - docker tag enigma-client:latest $CI_REGISTRY/$CI_REGISTRY_USER/enigma/client:latest

    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/enigma/server:latest
    - docker push $CI_REGISTRY/$CI_REGISTRY_USER/enigma/client:latest