stages:
  - lint
  - test

Lint:
  stage: lint
  image: python:3.12
  script:
    - pip install flake8
    - flake8

Test:
  stage: test
  image: python:3.12
  script:
    - pip install pytest
    - python3 -m pytest server/