[tool.ruff]

exclude = [
    ".venv",
    ".ruff_cache",
    "__pycache__",
    ".pytest_cache",
]

target-version = "py312"

[tool.ruff.lint]
select = [
    "I",  # isort
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"